#!/bin/bash
# 
# Alexis Desktop Manager - A Bash based desktop manager for Termux and Termux Proot 
# Copyright (C) 2022 Alexis Jhon Gaspar. 
# 
# This program is free software: you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version. 
# 
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details. 
# 
# You should have received a copy of the GNU General Public License # along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.

echo "Welcome to Alexis Desktop Manager for Termux! (Type H for help)"
read -p "Enter an option " screen

case "$screen" in
	L) printf "Here's a list of sessions:" \n "1. Put your DE here" \n "2. xterm" \n "3. User specific script" ; exit ;;
	H) echo "ADM command list" \n "H - This prompt" \n "L - List all possible sessions" \n "A - About this Script" \n "K - kill current session" \n "S - Setup" ; exit ;;
	A) echo " Alexis Desktop Manager" \n "by Lucss21a, improved by Damaj30Damaj" \n "©2022 by Lucss21a." \n "Licensed Under the GNU GPL v3." ; exit ;;
        K) echo "Which display?:" ; read -r screen1 ; vncserver -kill "$screen1" ; exit ;;
	S) echo "Enter your screen resolution (widthXheight): " ; read -r screen_res ; echo "Please select a session: " ; read -r session ;;
	*) printf "Invalid Input!, write H for help";;
esac

case "$session" in
	1) vncserver -name "Put your DE here" -geometry "$screen_res" ;;
	2) vncserver -name xterm -geometry "$screen_res" -xstartup ~/.vnc/xstartup2 ;;
	3) printf "Where is your xstartup file" ; read -r xstartup ; vncserver -name "My Desktop" -geometry "$screen_res" -xstartup $xstartup ;;
	*) printf "Invalid Output!" ;;
esac 
exit
